### PR TITLE
Switch dependencies to esl-erlang 

### PR DESCRIPTION
**Pull request by yalh76**
## Problem
- *https://github.com/YunoHost-Apps/pleroma_ynh/issues/64#issuecomment-482736431*

## Solution
- *Switch from erlang-dev to esl-erlang*

## PR Status
- [x] Code finished.
- [x] Tested with Package_check.
- [x] Fix or enhancement tested.
- [x] Upgrade from last version tested.
- [x] Can be reviewed and tested.

## Validation
---
- [ ] **Code review**
- [ ] **Approval (LGTM)**  
*Code review and approval have to be from a member of @YunoHost/apps group*
- **CI succeeded** : 
[Build Status/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/pleroma_ynh_PR73%20(yalh76)/)

When the PR is marked as ready to merge, you have to wait for 3 days before really merging it.

### CODE REVIEW

**Comment by yalh76** [comment]
If someone from the @YunoHost-Apps/apps-group can tell me is it's the good way to change dependencies during upgrade...

**Comment by maniackcrudelis** [comment]
No I don't think that's a good way to to it.
By using `ynh_package_autoremove` you remove the packages and all dependencies of those.
If another app have installed those packages, you're going to remove it anyway.

If you just change the dependencies of your package, those unneeded packages should be removed by the next execution of `apt autoremove` as unneeded dependencies.
Try it to be sure.

**Comment by yalh76** [comment]
I first tryed just to change the dependencies having `extra_pkg_dependencies="elixir esl-erlang"` but during upgrade, it should remove some dependencies so upgrade fails

As written in https://packages.erlang-solutions.com/debian/dists/stretch/contrib/binary-amd64/Packages, the new dependency `esl-erlang` has conflict, replaces and provide erlang-dev, erlang-tools, erlang-parsetools, erlang-xmerl

**Comment by maniackcrudelis** [comment]
Ok...
Then either you call `ynh_install_app_dependencies` multiple time, to let apt autoremove do its job, or you clearly remove the other packages.
If there's a conflict, you could indeed remove the other packages. But it could break other apps if their use it.

**Comment by yalh76** [comment]
Canceling the dependency switch as esl-erlang is not mandatory for elixir. 
It can use actual dependencies

**Pull request closed without merging**
