### PR TITLE
Upgrade to v2.8.0

### PR DESCRIPTION
**Pull request by yalh76**
Upgrade sources
- `main` v2.8.0: https://git.pleroma.social/pleroma/pleroma/-/releases/v2.8.0
- Close #280
- Close #278
- Close #277 
- Close #276
- Close #274

### CODE REVIEW

**Comment by yalh76** [comment]
!testme

**Comment by rakoo** [comment]
FINALLY 🥳

**Comment by RichardFoxworthy** [comment]
But it's still not available in the Yunohost catalogue 🤔

**Comment by yalh76** [comment]
> But it's still not available in the Yunohost catalogue 🤔

Should be available next saturday

**Comment by RichardFoxworthy** [comment]
Awesome! Thank you!

**Pull request merged**
