### PR TITLE
Fix registration choice not taken into account

### PR DESCRIPTION
**Pull request by fflorent**
## Problem

- When you ask for not opening the registration, the visitor still can create accounts. The choice is not taken into account.

## Solution

- Replace the value for the `registrations_open` key in the installation and change it on the upgrade from versions below `2.4.4~ynh2`

## PR Status

- [x] Code finished and ready to be reviewed/tested
- [x] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by fflorent** [comment]
!testme

**Comment by fflorent** [comment]
Up?

**Review by tituspijean — APPROVED** [review]
Looks good to me.

**Review by yalh76 — APPROVED** [review]
LGTM

**Pull request merged**
